In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

df = pd.read_csv('combined_and_transformed_data.csv')

df

actividad  sujeto         movil  actividad_cat  userID  gFx_mean  \
0     Standing  Alvaro  Unespecified              1       0  0.453964   
1     Standing  Alvaro  Unespecified              1       0  0.453949   
2     Standing  Alvaro  Unespecified              1       0  0.453913   
3     Standing  Alvaro  Unespecified              1       0  0.453945   
4     Standing  Alvaro  Unespecified              1       0  0.454027   
...        ...     ...           ...            ...     ...       ...   
8872   Walking   Marta  Unespecified              2      13  0.424058   
8873   Walking   Marta  Unespecified              2      13  0.424075   
8874   Walking   Marta  Unespecified              2      13  0.423986   
8875   Walking   Marta  Unespecified              2      13  0.423832   
8876   Walking   Marta  Unespecified              2      13  0.423721   

      gFy_mean  gFz_mean  TgF_mean  gFx_energia  ...  gFz_energia  \
0     0.215190  0.714026  1.028427     0.000002  ...     0.000008   
1     0.215213  0.714001  1.028377     0.000002  ...     0.000008   
2     0.215260  0.714070  1.028515     0.000002  ...     0.000009   
3     0.215294  0.714116  1.028607     0.000002  ...     0.000009   
4     0.215309  0.714124  1.028635     0.000002  ...     0.000009   
...        ...       ...       ...          ...  ...          ...   
8872  0.732716  0.261309  1.003285     0.001295  ...     0.001842   
8873  0.733161  0.261598  1.004203     0.001298  ...     0.001845   
8874  0.733822  0.262531  1.005702     0.001299  ...     0.001852   
8875  0.734330  0.262427  1.006647     0.001294  ...     0.001859   
8876  0.734868  0.261389  1.007470     0.001294  ...     0.001892   

      TgF_energia  gFx_median  gFy_median  gFz_median  TgF_median  \
0        0.000032    0.453907    0.215169    0.714091       1.029   
1        0.000034    0.453907    0.215328    0.714091       1.029   
2        0.000034    0.453907    0.215328    0.714192       1.029   
3        0.000034    0.453907    0.215328    0.714192       1.029   
4        0.000034    0.453907    0.215328    0.714192       1.029   
...           ...         ...         ...         ...         ...   
8872     0.006521    0.424831    0.720719    0.253920       0.974   
8873     0.006468    0.424955    0.722278    0.254525       0.980   
8874     0.006449    0.424831    0.724974    0.255155       0.989   
8875     0.006482    0.424831    0.725238    0.255205       0.989   
8876     0.006576    0.424955    0.725238    0.254147       0.989   

      gFx_kurtosis  gFy_kurtosis  gFz_kurtosis  TgF_kurtosis  
0        -0.204074      1.295220      3.594879      3.564981  
1        -0.216089      1.218556      3.279499      3.253851  
2        -0.157667      1.253833      3.032582      3.002477  
3         0.075939      1.094705      3.030501      2.999445  
4         0.017434      1.081896      3.108663      3.065008  
...            ...           ...           ...           ...  
8872      0.508609     -0.085918      4.629178     -0.292049  
8873      0.491520     -0.081640      4.564161     -0.289616  
8874      0.480225     -0.128577      4.377897     -0.334548  
8875      0.497333     -0.209992      4.338872     -0.396065  
8876      0.491419     -0.333030      4.252318     -0.480360  

[8877 rows x 21 columns]

In [2]:
# Read train and test datasets
df_train = pd.read_csv('train_data.csv')
df_test = pd.read_csv('test_data.csv')

In [3]:
# Select most-correlated features
df_train.corr()['actividad_cat'].sort_values(ascending = False, key=np.abs)

actividad_cat    1.000000
TgF_energia     -0.321983
gFy_energia     -0.126610
gFx_mean        -0.105893
gFx_energia     -0.103855
gFx_median      -0.102624
TgF_median       0.074741
gFz_energia     -0.068727
gFy_median      -0.051967
gFy_mean        -0.051906
gFz_kurtosis     0.016024
gFz_median       0.013870
gFz_mean         0.012299
gFx_kurtosis     0.011247
gFy_kurtosis     0.009315
TgF_mean        -0.008977
TgF_kurtosis     0.005150
userID          -0.000561
Name: actividad_cat, dtype: float64

In [4]:
# Split the data into X and y sets
y_test = df_test['actividad_cat']
y_train = df_train['actividad_cat']

X_test = df_test.drop(columns={'actividad_cat', 'sujeto', 'actividad', 'gFz_mean', 'movil', 'userID', 'TgF_kurtosis', 'gFy_kurtosis', 'gFz_median'}, axis = 1)
X_train = df_train.drop(columns={'actividad_cat', 'sujeto', 'actividad', 'gFz_mean', 'movil', 'userID', 'TgF_kurtosis', 'gFy_kurtosis', 'gFz_median'}, axis = 1)

X_train

gFx_mean  gFy_mean  TgF_mean  gFx_energia  gFy_energia  gFz_energia  \
0     0.453964  0.215190  1.028427     0.000002     0.000001     0.000008   
1     0.453949  0.215213  1.028377     0.000002     0.000001     0.000008   
2     0.453913  0.215260  1.028515     0.000002     0.000001     0.000009   
3     0.453945  0.215294  1.028607     0.000002     0.000001     0.000009   
4     0.454027  0.215309  1.028635     0.000002     0.000001     0.000009   
...        ...       ...       ...          ...          ...          ...   
7298  0.402794  0.675592  0.988920     0.001973     0.002562     0.004624   
7299  0.403589  0.676142  0.990363     0.001950     0.002544     0.004578   
7300  0.405153  0.677355  0.992855     0.001890     0.002459     0.004582   
7301  0.406693  0.678968  0.997355     0.001852     0.002377     0.004459   
7302  0.407825  0.680616  1.002628     0.001821     0.002337     0.004189   

      TgF_energia  gFx_median  gFy_median  TgF_median  gFx_kurtosis  \
0        0.000032    0.453907    0.215169      1.0290     -0.204074   
1        0.000034    0.453907    0.215328      1.0290     -0.216089   
2        0.000034    0.453907    0.215328      1.0290     -0.157667   
3        0.000034    0.453907    0.215328      1.0290      0.075939   
4        0.000034    0.453907    0.215328      1.0290      0.017434   
...           ...         ...         ...         ...           ...   
7298     0.011046    0.403849    0.662421      0.9685     -0.262566   
7299     0.010875    0.406080    0.663584      0.9710     -0.209149   
7300     0.010561    0.408310    0.665909      0.9730     -0.103057   
7301     0.009929    0.410499    0.668155      0.9790     -0.040293   
7302     0.009331    0.413184    0.671195      0.9870      0.038807   

      gFz_kurtosis  
0         3.594879  
1         3.279499  
2         3.032582  
3         3.030501  
4         3.108663  
...            ...  
7298     -0.150601  
7299     -0.110387  
7300     -0.123802  
7301     -0.032872  
7302      0.141965  

[7303 rows x 12 columns]

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, f1_score

# Fit and train the logistic regression model
log_reg = LogisticRegression(max_iter=500, 
                             random_state=0, 
                             penalty='none',
                             solver = 'lbfgs',
                             class_weight='balanced')

log_reg.fit(X_train, y_train)

# Predict the classes using the test set
y_pred = log_reg.predict(X_test)

# Generate the confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix\n", confusion_mat)

# Calculate F1-score
f1 = f1_score(y_test, y_pred, average='weighted')
print("\n F1 score : %.2f" % f1)

Confusion Matrix
 [[337   2 226]
 [  0 517  15]
 [ 32   9 436]]

 F1 score : 0.82


In [6]:
# Guardamos el modelo en formato .sav
import pickle

pickle.dump(log_reg, open("logistic_regression_model.sav", "wb"))